version: 1
formatters:
    standard:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
    detailed:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s - %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: standard
        stream: ext://sys.stdout

    file:
        class: logging.FileHandler
        level: DEBUG
        formatter: detailed
        filename: output/logs/m5_forecasting.log
        mode: a
        encoding: utf-8

loggers:
    src.data:
        level: DEBUG
        handlers: [console, file]
        propagate: no

    src.models:
        level: DEBUG
        handlers: [console, file]
        propagate: no

    src.visualization:
        level: INFO
        handlers: [console, file]
        propagate: no

    src.utils:
        level: DEBUG
        handlers: [console, file]
        propagate: no

root:
    level: INFO
    handlers: [console, file]
